// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"database/sql"
	"github.com/compico/shopsite/internal/database"
	"github.com/compico/shopsite/internal/di"
)

import (
	_ "github.com/compico/shopsite/internal/cmd/commands/migrate/migrations"
)

// Injectors from wire.go:

func InitializeMigrator(configPath string, dsnArgs di.DsnParams) (migrator, error) {
	config, err := di.ProviderConfig(configPath)
	if err != nil {
		return migrator{}, err
	}
	databaseConfig := di.ProviderDataBaseConfigWithParams(config, dsnArgs)
	db, err := database.NewConnection(databaseConfig)
	if err != nil {
		return migrator{}, err
	}
	sqlDB, err := di.ProviderDatabaseTx(db)
	if err != nil {
		return migrator{}, err
	}
	migrateMigrator := migrator{
		conf:       databaseConfig,
		connection: sqlDB,
	}
	return migrateMigrator, nil
}

// wire.go:

type (
	migrator struct {
		conf       Config
		connection *sql.DB
	}

	Config interface {
		GetDSN() string
		AddParams(...string)
		GetDialect() string
	}
)
